### ISSUE TITLE
Allow for easier deserialization of DCV validation details in response

### ISSUE THREAD

**Issue by sciros** [open-mpic/aws-lambda-python#18]
In `MpicResponseBuider` can potentially add `exclude_none=True`:

```python
'body': json.dumps(response_body.model_dump(exclude_none=True))
```

That's a reasonable change in `MpicResponseBuilder` and it'll just need a corresponding unit test in `test_mpic_response_builder`. An alternative would be to more explicitly define the two objects in Python which _may_ be a better solution.
Something to consider.

See https://github.com/open-mpic/open-mpic-specification/issues/8#issuecomment-2388738296

**Comment by birgelee** [comment]
I somewhat favor the two object solution as this more closely matches the Open MPIC spec. I feel it is helpful to have the spec defined that way as it can more tightly enforce the call semantics at the Open API level.

The exclude_none approach also can also be applied more broadly. There are some fields like "errors" which can be present or not. Unlike optional fields on the API calls, api responses tend to contain all the optional fields with none values. At the moment I can't tell if this is good or bad, but I think it is something worth considering.

**Comment by birgelee** [comment]
Merged in. Closing
